services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mail2chat
    volumes:
      - mail2chat-db:/var/lib/mysql
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - default

  backend:
    build:
      context: ./backend
      target: development
    working_dir: /app
    command: >
      sh -c "npx prisma generate && \
             npx prisma migrate deploy && \
             npm run start:dev"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/mail2chat
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/logs:/app/logs
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/tsconfig.build.json:/app/tsconfig.build.json
      - ./backend/nest-cli.json:/app/nest-cli.json
      - /app/node_modules
    ports:
      - "${BACKEND_PORT:-3050}:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  client:
    command: sh -c "npm install && npm run dev -- -p 3000"
    working_dir: /app
    environment:
      - BACKEND_INTERNAL_URL=http://backend:3000
      - NEXT_PUBLIC_API_URL=http://backend:3000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - default

volumes:
  mail2chat-db:
