services:
  backend:
    build:
      context: ./backend
      target: deps
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT:-3001}:3000"
    networks:
      - default
      - mail2chat_default
  client:
    command: sh -c "npm install && npm run dev -- -p 3000"
    working_dir: /app
    environment:
      - BACKEND_INTERNAL_URL=http://backend:3000
      - NEXT_PUBLIC_API_URL=http://backend:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

networks:
  mail2chat_default:
    external: true
    # No host port exposure; access via client proxy rewrites
